# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-10 05:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myname', models.CharField(blank=True, max_length=30, null=True)),
                ('myemail', models.CharField(blank=True, max_length=30, null=True)),
                ('myphone', models.CharField(blank=True, max_length=20, null=True)),
                ('introduction', models.CharField(blank=True, default='안녕하세요!', max_length=100)),
                ('myid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
