# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-11 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0002_auto_20190511_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
