# Generated by Django 2.2.2 on 2019-06-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0005_profile_changed_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='changed_password',
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_profile_followers_+', to='Member.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='_profile_following_+', to='Member.Profile'),
        ),
    ]
