# Generated by Django 2.2.2 on 2019-06-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0006_auto_20190617_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, to='Member.Profile'),
        ),
    ]
