# Generated by Django 2.2.2 on 2019-06-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0007_auto_20190618_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_profile_followers_+', to='Member.Profile'),
        ),
    ]
