# Generated by Django 2.2.1 on 2019-06-18 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0009_profile_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follow',
        ),
    ]
