# Generated by Django 2.2.1 on 2019-06-18 11:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Member', '0012_auto_20190618_1955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follower',
            new_name='Follow',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='follower_profile',
            new_name='follow_profile',
        ),
        migrations.DeleteModel(
            name='Following',
        ),
    ]
