# Generated by Django 2.2.1 on 2019-06-18 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Member', '0013_auto_20190618_2012'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='Follower',
        ),
        migrations.RenameField(
            model_name='follower',
            old_name='follow_profile',
            new_name='follower_profile',
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Member.Profile')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
