# Generated by Django 2.2.2 on 2019-06-18 14:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0014_auto_20190618_2203'),
        ('Posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='ch add date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Member.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=100),
        ),
    ]
