# Generated by Django 2.2.2 on 2019-06-19 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posting', '0005_auto_20190619_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=255)),
                ('rub_date', models.DateTimeField(verbose_name='ch add date')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Posting.Post')),
            ],
            options={
                'ordering': ['rub_date'],
            },
        ),
    ]
